# Generated by Django 5.0.2 on 2024-02-23 08:40

from django.db import migrations
from shop.models import Item


def populate_items(apps, schema_editor):
    Item = apps.get_model('shop', 'Item')

    items_to_add = [
        {'item': 'Sugar', 'unit': 'kg', 'price': 180},
        {'item': 'Rice', 'unit': 'kg', 'price': 220},
        {'item': 'maize flour', 'unit': 'kg', 'price': 150},
        {'item': 'milk', 'unit': 'L', 'price': 70},
        {'item': 'Cooking oil', 'unit': 'L', 'price': 150},
        {'item': 'soap', 'unit': 'piece', 'price': 65},
    ]

    for item_data in items_to_add:
        Item.objects.create(**item_data)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_order_item_id_order_items'),
    ]

    operations = [
        migrations.RunPython(populate_items),
    ]
